-- MODELAMIENTO DE BASES DE DATOS 001A

-- PROYECTO SEMANA 6 - CONSULTORIO MEDICO MUNICIPALIDAD SANTA GEMA 

-- GRUPO N°10
-- SEBASTIAN RODRIGUEZ / MATIAS SUAREZ

/* 
===================================
    CREACION USUARIO SOLICITADO
===================================
*/

CREATE USER PRY2204_S6 
IDENTIFIED BY "PRY2204.semana_6"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2204_S6;

GRANT RESOURCE TO PRY2204_S6;

ALTER USER PRY2204_S6 DEFAULT ROLE RESOURCE;


/* 
================================
    ELIMINACION DE TABLAS
================================
*/

DROP TABLE DOSIS;
DROP TABLE MEDICAMENTO;
DROP TABLE VIA_ADMINISTRA;
DROP TABLE TIPO_MEDIC;
DROP TABLE MARCA;

DROP TABLE MEDICO_ESPEC;
DROP TABLE ESPECIALIDAD;

DROP TABLE PAGO;
DROP TABLE METODO_PAGO;
DROP TABLE BANCO;

DROP TABLE RECETA;
DROP TABLE TIPO_RECETA;
DROP TABLE DIAGNOSTICO;
DROP TABLE MEDICO;
DROP TABLE DIGITADOR;
DROP TABLE PACIENTE;

DROP TABLE COMUNA;
DROP TABLE CIUDAD;
DROP TABLE REGION;


/* 
====================================
    CREACION DE TABLAS INICIALES
       Y CLAVES PRIMARIAS
====================================
*/

CREATE TABLE BANCO 
( 
cod_banco NUMBER (6) NOT NULL, 
nombre VARCHAR2 (50) NOT NULL,

CONSTRAINT PK_BANCO PRIMARY KEY (cod_banco)
);

CREATE TABLE CIUDAD 
( 
cod_ciudad NUMBER (6) NOT NULL , 
nom_ciudad VARCHAR2 (25) NOT NULL , 
REGION_cod_region NUMBER (6) NOT NULL,

CONSTRAINT PK_CIUDAD PRIMARY KEY (cod_ciudad)
);

CREATE TABLE COMUNA 
( 
cod_comuna NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1101 INCREMENT BY 1), 
nom_comuna VARCHAR2 (25) NOT NULL, 
CIUDAD_cod_ciudad NUMBER (6) NOT NULL,

CONSTRAINT PK_COMUNA PRIMARY KEY (cod_comuna)
);

CREATE TABLE DIAGNOSTICO 
( 
cod_diagnostico NUMBER (6) NOT NULL, 
nombre VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (cod_diagnostico)
);

CREATE TABLE DIGITADOR 
( 
cod_digitador NUMBER (6) NOT NULL, 
rut_dig NUMBER (11) NOT NULL, 
dv_dig CHAR (1) NOT NULL, 
pnombre VARCHAR2 (25) NOT NULL, 
snombre VARCHAR2 (25), 
papellido VARCHAR2 (25) NOT NULL, 
sapellido VARCHAR2 (25),

CONSTRAINT PK_DIGITADOR PRIMARY KEY (cod_digitador)
);

CREATE TABLE DOSIS 
( 
MEDICAMENTO_cod_medicamento NUMBER (7) NOT NULL, 
RECETA_cod_receta NUMBER (7) NOT NULL, 
cantidad_medicamento NUMBER (3) NOT NULL, 
descrip_dosis VARCHAR2 (30) NOT NULL, 
dias_tratamiento NUMBER (3) NOT NULL,

CONSTRAINT PK_DOSIS PRIMARY KEY (MEDICAMENTO_cod_medicamento, RECETA_cod_receta)
);

CREATE TABLE ESPECIALIDAD 
( 
cod_especialidad NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
descripcion VARCHAR2 (50) NOT NULL,

CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (cod_especialidad)
);

CREATE TABLE MARCA 
( 
cod_marca NUMBER (6) NOT NULL, 
nombre VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_MARCA PRIMARY KEY (cod_marca)
);

CREATE TABLE MEDICAMENTO 
( 
cod_medicamento NUMBER (7) NOT NULL, 
nombre VARCHAR2 (25) NOT NULL, 
stock INTEGER  NOT NULL,
dosis_recomendada VARCHAR2 (30) NOT NULL, 
TIPO_MEDIC_cod_tipo_med NUMBER (6) NOT NULL, 
VIA_ADMINISTRA_cod_via NUMBER (6) NOT NULL, 
MARCA_cod_marca NUMBER (6) NOT NULL,

CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (cod_medicamento) 
);

CREATE TABLE MEDICO 
( 
rut_med NUMBER (11) NOT NULL, 
dv_med CHAR (1) NOT NULL, 
pnombre VARCHAR2 (25) NOT NULL, 
snombre VARCHAR2 (25), 
papellido VARCHAR2 (25) NOT NULL, 
sapellido VARCHAR2 (25), 
telefono VARCHAR2 (15) NOT NULL,

CONSTRAINT PK_MEDICO PRIMARY KEY (rut_med)
);

CREATE TABLE MEDICO_ESPEC 
( 
MEDICO_rut_med NUMBER (11)  NOT NULL, 
ESPECIALIDAD_cod_especialidad NUMBER (6) NOT NULL,

CONSTRAINT FK_MEDICO_ESPEC PRIMARY KEY (MEDICO_rut_med, ESPECIALIDAD_cod_especialidad)
);

CREATE TABLE METODO_PAGO 
( 
cod_pago NUMBER (6) NOT NULL , 
descripcion VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_METODO_PAGO PRIMARY KEY (cod_pago)
);

CREATE TABLE PACIENTE 
( 
rut_pac NUMBER (11) NOT NULL, 
dv_pac CHAR (1) NOT NULL, 
pnombre VARCHAR2 (25) NOT NULL, 
snombre VARCHAR2 (25), 
edad NUMBER (3) NOT NULL, 
telefono NUMBER (11) NOT NULL, 
calle VARCHAR2 (25) NOT NULL , 
numeracion NUMBER (5) NOT NULL , 
COMUNA_cod_comuna NUMBER (6) NOT NULL,

CONSTRAINT PK_PACIENTE PRIMARY KEY (rut_pac)
);

CREATE TABLE PAGO 
( 
cod_boleta NUMBER (8) NOT NULL, 
fecha_boleta DATE NOT NULL, 
monto_total NUMBER (9) NOT NULL, 
METODO_PAGO_cod_pago NUMBER (6) NOT NULL, 
BANCO_cod_banco NUMBER (6) NOT NULL, 
RECETA_cod_receta NUMBER (7) NOT NULL,

CONSTRAINT PK_PAGO PRIMARY KEY (cod_boleta)
);

CREATE TABLE RECETA 
( 
cod_receta NUMBER (7) NOT NULL, 
observaciones VARCHAR2 (500), 
fecha_emision DATE NOT NULL, 
fecha_venc DATE, 
TIPO_RECETA_cod_tipo_rec NUMBER (6) NOT NULL, 
MEDICO_rut_med NUMBER (11) NOT NULL, 
PACIENTE_rut_pac NUMBER (11) NOT NULL, 
DIAGNOSTICO_cod_diagnostico NUMBER (6) NOT NULL, 
DIGITADOR_cod_digitador NUMBER (6) NOT NULL,

CONSTRAINT PK_RECETA PRIMARY KEY (cod_receta)
);

CREATE TABLE REGION 
( 
cod_region NUMBER (6) NOT NULL , 
nom_region VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_REGION PRIMARY KEY (cod_region)
);

CREATE TABLE TIPO_MEDIC 
( 
cod_tipo_med NUMBER (6) NOT NULL, 
nombre VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_TIPO_MEDIC PRIMARY KEY (cod_tipo_med)
);

CREATE TABLE TIPO_RECETA 
( 
cod_tipo_rec NUMBER (6) NOT NULL, 
descripcion VARCHAR2 (50) NOT NULL,

CONSTRAINT PK_TIPO_RECETA PRIMARY KEY (cod_tipo_rec)
);

CREATE TABLE VIA_ADMINISTRA 
( 
cod_via NUMBER (6) NOT NULL , 
descripcion VARCHAR2 (25) NOT NULL,

CONSTRAINT PK_VIA_ADMINISTRA PRIMARY KEY (cod_via)
);


/* 
====================================
    CREACION DE CLAVES FORANEAS
====================================
*/

ALTER TABLE CIUDAD ADD CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY (REGION_cod_region) REFERENCES REGION (cod_region);

ALTER TABLE COMUNA ADD CONSTRAINT FK_COMUNA_CIUDAD FOREIGN KEY (CIUDAD_cod_ciudad) REFERENCES CIUDAD (cod_ciudad);

ALTER TABLE DOSIS ADD CONSTRAINT FK_DOSIS_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_cod_medicamento) REFERENCES MEDICAMENTO (cod_medicamento);

ALTER TABLE DOSIS ADD CONSTRAINT FK_DOSIS_RECETA FOREIGN KEY (RECETA_cod_receta) REFERENCES RECETA (cod_receta);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT FK_MEDICAMENTO_MARCA FOREIGN KEY (MARCA_cod_marca) REFERENCES MARCA (cod_marca);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT FK_MEDICAMENTO_TIPO_MEDIC FOREIGN KEY (TIPO_MEDIC_cod_tipo_med) REFERENCES TIPO_MEDIC (cod_tipo_med);

ALTER TABLE MEDICAMENTO ADD CONSTRAINT FK_MEDICAMENTO_VIA_ADMINISTRA FOREIGN KEY (VIA_ADMINISTRA_cod_via) REFERENCES VIA_ADMINISTRA (cod_via);

ALTER TABLE MEDICO_ESPEC ADD CONSTRAINT FK_MEDICO_ESPEC_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_cod_especialidad) REFERENCES ESPECIALIDAD (cod_especialidad);

ALTER TABLE MEDICO_ESPEC ADD CONSTRAINT FK_MEDICO_ESPEC_MEDICO FOREIGN KEY (MEDICO_rut_med) REFERENCES MEDICO (rut_med);

ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_COMUNA FOREIGN KEY (COMUNA_cod_comuna) REFERENCES COMUNA (cod_comuna);

ALTER TABLE PAGO ADD CONSTRAINT FK_PAGO_BANCO FOREIGN KEY (BANCO_cod_banco) REFERENCES BANCO (cod_banco);

ALTER TABLE PAGO ADD CONSTRAINT FK_PAGO_METODO_PAGO FOREIGN KEY (METODO_PAGO_cod_pago) REFERENCES METODO_PAGO (cod_pago);

ALTER TABLE PAGO ADD CONSTRAINT FK_PAGO_RECETA FOREIGN KEY (RECETA_cod_receta) REFERENCES RECETA (cod_receta);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_DIAGNOSTICO FOREIGN KEY (DIAGNOSTICO_cod_diagnostico) REFERENCES DIAGNOSTICO (cod_diagnostico);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_DIGITADOR FOREIGN KEY (DIGITADOR_cod_digitador) REFERENCES DIGITADOR (cod_digitador);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_MEDICO FOREIGN KEY (MEDICO_rut_med) REFERENCES MEDICO (rut_med);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_PACIENTE FOREIGN KEY (PACIENTE_rut_pac) REFERENCES PACIENTE (rut_pac);

ALTER TABLE RECETA ADD CONSTRAINT FK_RECETA_TIPO_RECETA FOREIGN KEY (TIPO_RECETA_cod_tipo_rec) REFERENCES TIPO_RECETA (cod_tipo_rec);


/* 
====================================
    CREACION DE CASOS CON ALTER
            CASO 1
====================================
*/

-- Los médicos deben tener un teléfono localizable. Este número telefónico debe ser único en la base de datos, es decir, dos o más médicos no pueden tener el mismo número telefónico.
ALTER TABLE MEDICO ADD CONSTRAINT UN_MEDICO_telefono UNIQUE (telefono);

-- El dígito verificador de los pacientes, médicos y digitadores solo deben permitir los valores 0 al 9 y la letra K.
ALTER TABLE DIGITADOR ADD CONSTRAINT CK_DIGITADOR_DV CHECK (dv_dig IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE MEDICO ADD CONSTRAINT CK_MEDICO_DV CHECK (dv_med IN ('0','1','2','3','4','5','6','7','8','9','K'));

ALTER TABLE PACIENTE ADD CONSTRAINT CK_PACIENTE_DV CHECK (dv_pac IN ('0','1','2','3','4','5','6','7','8','9','K'));


/* 
====================================
    CASO 2 - ALTERs ADCIONALES
====================================
*/

-- Agregar el precio unitario de cada medicamento.
ALTER TABLE MEDICAMENTO ADD precio_unit NUMBER (7) NOT NULL;

-- Se conoce que el precio de un medicamento oscila entre los $1.000 y los $2.000.000 de pesos.
ALTER TABLE MEDICAMENTO ADD CONSTRAINT CK_MEDICAMENTO_PRECIO CHECK (precio_unit BETWEEN 1000 AND 2000000);

-- Se definió que los métodos de pagos pueden ser: EFECTIVO, TARJETA, TRANSFERENCIA. Por lo tanto, debes agregar esta restricción.
ALTER TABLE METODO_PAGO ADD CONSTRAINT CK_METODO_PAGO CHECK (descripcion IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));

-- se debe eliminar la columna edad, y en su reemplazo agregar la fecha de nacimiento del paciente.
ALTER TABLE PACIENTE DROP COLUMN edad;

ALTER TABLE PACIENTE ADD (fecha_nacimiento DATE);

